### PR TITLE
Too-many-symbol-files

### PR DESCRIPTION
**Pull request by alyakan**

### CODE REVIEW

**Comment by alaeddineG** [comment]
Any update one when this fix will be merged and release on the official pipeline ?

**Comment by Kmohamed** [comment]
@alaeddineG did the custom build works fine with you ?

**Comment by alaeddineG** [comment]
To be honest I didn't test it. But i'm wondering if this would be part of your Official release. ( We do not go to production on our app with custom SDK this our rules :) )

**Comment by kdawgwilk** [comment]
I did try this branch out and the fix has been working for us for a month or two but we would like to get this into master to get the other bug fixes

**Comment by Kmohamed** [comment]
It will be included in the next release.

**Comment by kdawgwilk** [comment]
Was this released?

**Comment by Kmohamed** [comment]
@kdawgwilk Could you try the latest release I think we will not need this script.
could you give it a try ?

**Comment by vascome** [comment]
I still have this issue on latest 7.9.2 release

**Comment by Kmohamed** [comment]
@vascome could you please update cocoapods to 1.4.0 it should fix this warning

**Comment by vascome** [comment]
@Kmohamed thank you! it works

**Comment by Kmohamed** [comment]
@vascome urw

**Pull request closed without merging**
