### PR TITLE
revert/fix carthage

### PR DESCRIPTION
**Pull request by Figo0o**

### CODE REVIEW

**Comment by txaiwieser** [comment]
🙄

**Comment by Figo0o** [comment]
Hello @txaiwieser, Yep this seems awkward I know, but it's fixed. give it a try :)

**Comment by txaiwieser** [comment]
Bootstrapping Carthage doesnt download InstabugCore anymore. It was removed? Should I remove from the project?

**Comment by Figo0o** [comment]
Well, there is an issue and I'm fixing it right away. Will notify you so. 

So sorry for the inconvenience!

**Comment by Figo0o** [comment]
Just noticed something, are you sure that you have added those both into the `Cartfile` ?
```
binary "https://raw.githubusercontent.com/Instabug/Instabug-iOS/master/Carthage.json"
binary "https://raw.githubusercontent.com/Instabug/Instabug-iOS/master/InstabugCore/Carthage.json"
```

**Comment by txaiwieser** [comment]
I wasn't using both, your readme doesn't say that. I think when you make big changes like this one you guys should make a migration guide and a big bump version 👍

**Comment by Figo0o** [comment]
We do apologize for that so much, and you are totally right, we really appreciate your feedback and will keep that in mind in the next big changes. 🙂

Sorry for the inconvenience again! ✋

**Comment by txaiwieser** [comment]
Thanks for the help! Keep with the good work! 👍

**Pull request merged**
