### PR TITLE
User flag to skip dSYM uploads

### PR DESCRIPTION
**Pull request by jlmendezbonini**
I don't expect you to merge this pull request, but in my projects I use a user-defined setting like the one in this pull request to optionally disable the dSYM upload.  Being able to optionally disable dSYM uploads is a much desired configuration option.

### CODE REVIEW

**Comment by msoliman** [comment]
Actually we have another branch "no_build_script" for exactly this reason. I'd recommend you to use it instead, if you don't want to upload dSYM files, because we do keep it updated with each release of the SDK. Just link your podfile to the other branch instead of the default branch

**Comment by jlmendezbonini** [comment]
Can you provide and example of the `Podfile` configuration that you use? I've been trying a few different option and can't get it to work properly.  In our setup we need to disable the `dSYM` upload on a build configuration basis.

**Comment by msoliman** [comment]
Here's a sample to disable it entirely:
pod 'Instabug', :git => 'https://github.com/Instabug/Instabug-iOS.git', :branch => 'no_build_script'

**Comment by jlmendezbonini** [comment]
I did that, but what we need is to be able to enable/disable Instabug on a build configuration basis.  If I were translate that to a CocoaPods (non working) config file it'd be something more like:
```
pod 'Instabug', :configurations => ['Debug'] , :branch => 'no_build_script'
pod 'Instabug', :configurations => ['Beta']
```

**Comment by msoliman** [comment]
Just saw this, sorry for the late reply.

If you want to have it based on the build configuration, you can't set it from the Podfile then, because it runs once per `pod install`. Instead you'll have to do something similar to this PR, where you check for the condition in the build script itself.

I'd say add this to the beginning of the build script:
```
if [ $CONFIGURATION = "Debug" ]; then
    exit 0
fi
```

**Pull request closed without merging**
